sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.3

before_install: gem install bundler -v 1.17.2

notifications:
  slack:
    secure: kIiEL5CXmTaNDWGV3SIv4XZWFmif1O/DvHU4RPAelagfxrQs8pwM0C74dE5Ay1pOtdcBkfllZN35hMQtotVQxc6ENe23FoOHZrqjWPSZlZpqv+3bwadAZJocXDBn9Fcd4UxOE+0l+oNb4cjqKofZJkZrrmTrEt30hZY6bduajZWSLwFomcsjy+uQX5UvRLMd6bQuFVrG7Ud2ALjG+f2HbCofmqwukc9ctdNoZXHZyx3oBp4nE0pFZOR7Ftw9v4sncARqTM//PxMhJTMSjxG0XeW+U3XFKCU3o+Ytow8I7TJ9PISfhM0Trn59Dy7MvXxNWFIndwfz+3Izr9W106hNh6956sTpo/+r0rTR19MvQxZpljUSE3DdvCKrXF8zqZhQwveYs5crhL8PPUj+RICqXyBTEGJU9BfRnGlLGh2CHh47W1hV+BpzO2oOQMCu5UOseYE1NRyTw3Jts5iPSuxglwkxtOW1frlKpy+YIcZb6Ig4ZJ6XrNoUkpr4bMeFbJIfAIPMNmnyUyBxoy50X2aLSDNRodC8TmFjbO75BnkDoHdIRL9eq6Hvh2UaLVJs2FbjQxHRY8Hz06Z3+pbKesXhai2zUg4wlFjWmD5mQjwUYIA3yzEJvExw82FFbTzOg7qQil7rCdbYETL0iPxy5X/D0Jz6MpBza54v9tjVYbB2gAo=
